### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by Goddard** [Virtuallified/REST-Api_JWT_CodeIgniter3#1]
Need a way to install with composer on an existing project

**Comment by Virtuallified** [comment]
> Need a way to install with composer on an existing project

- First copy and paste composer.json file in the project folder to the application folder
- Second in the config.php file 

`$config['composer_autoload'] = TRUE;`

That way you can successfully integrate composer in your CodeIgniter project.

**Comment by Goddard** [comment]
This doesn't fix the issue.
