### ISSUE TITLE
Need of JWT?

### ISSUE THREAD

**Issue by ahgsql** [Virtuallified/REST-Api_JWT_CodeIgniter3#5]
Hey, thanks for this project. While i was experimenting with this, i realized CI, automatically creates session and puts all data into it then sent this in cookie. Then on following requests, checking cookies then matches related session with it. So i am trying to implement react Login and auth system without jwt token, just bare sessions.

In your code, you are both sending JWT, and creating session for it. I couldn't understand the principle behind this. If we want to use JWT's we dont need sessions, if sessions are included in cookie, its OK to go with cookie and session based system if security concerns are not too much.

**Comment by Virtuallified** [comment]
Hi @ahgsql, 
Yes, for your case you can go with that, approach.
For this project I added the JWT for API authentication. Not for login,
For login/signup we can use session.
